version: 2

project_name: clipse

before:
  hooks:
    - go mod tidy

builds:
  # Linux Wayland (no CGO)
  - id: linux-wayland
    binary: clipse
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    tags:
      - wayland
    env:
      - CGO_ENABLED=0

  - id: linux-x11-amd64
    binary: clipse
    goos:
      - linux
    goarch:
      - amd64
    tags:
      - linux
    env:
      - CGO_ENABLED=1

  - id: linux-x11-arm64
    binary: clipse
    goos:
      - linux
    goarch:
      - arm64
    tags:
      - linux
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc

  - id: darwin
    binary: clipse
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - darwin
    env:
      - CGO_ENABLED=1

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}

checksum:
  name_template: checksums.txt

release:
  github:
    owner: savedra1
    name: clipse
