version: 2

project_name: clipse

before:
  hooks:
    - go mod tidy

builds:
  # =========================
  # Linux – Wayland (no CGO)
  # =========================
  - id: linux-wayland
    binary: clipse
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    tags:
      - wayland
    env:
      - CGO_ENABLED=0

  # =========================
  # Linux – X11 (CGO)
  # =========================
  - id: linux-x11
    binary: clipse
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    tags:
      - linux
    env:
      - CGO_ENABLED=1

  # =========================
  # macOS (CGO + AppKit)
  # =========================
  - id: darwin
    binary: clipse
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - darwin
    env:
      - CGO_ENABLED=1
      - CC=o64-clang # optional but recommended

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .BuildID }}_{{ .BuildID }}{{ end }}

checksum:
  name_template: checksums.txt

release:
  github:
    owner: savedra1
    name: clipse
