# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds: # default
  - id: linux-wayland
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    tags:
      - wayland
    ldflags:
      - -s -w
    # No tags needed - X11 is default

  # Linux Wayland
  - id: linux-x11
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    binary: "{{ .ProjectName }}-x11"

  # macOS (native, no X11/Wayland)
  - id: darwin
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    builds:
      - linux-wayland
      - darwin
      - linux-x11
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
