name: Add Owner as Reviewer

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  add-reviewer:
    if: github.event.pull_request.user.login != 'savedra1'
    runs-on: ubuntu-latest
    steps:
      - name: Add Repo Owner as Reviewer
        uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
        with: 
          reviewers: "savedra1"
          token: ${{ secrets.GITHUB_TOKEN }}